In [34]:
#Using Hashtags and Regex, tag tweets by candidate mention

#NOTE:  hashtags do not seem to add much so leaving them out for now, code commented out.

In [1]:
keywords = {}

keywords['Trump'] = ['trump']
keywords['Clinton'] = ['hillary', 'clinton']
keywords['Sanders'] = ['bern', 'sanders']
keywords['Cruz'] = ['cruz']
keywords['Rubio'] = ['marco', 'rubio']
keywords['Kasich'] = ['kasich']
keywords['Bush'] = ['jebbush','jeb', '#bush']
keywords['Christie'] = ['chrischristie', 'chris christie','christie2016','#christie']
keywords['Huckabee'] = ['huckabee']
keywords['Omally'] = ['omally']
keywords['Randpaul'] = ['rand paul','randpaul']
keywords['Fiorina'] = ['carly', 'carlley', 'fiorina']
keywords['Carson'] = ['ben carson', 'bencarson', 'bencarson', '#carson', 'bencarson2016', 'carson2016', 'votecarson', 'bencarson4prez', 'carson4prez', 'carsonstrong', 'respectcarson', 'drbencarson']

In [3]:
# #selected hashtags pre generated and stored in files ordered by frequency
# import pandas as pd
import pandas as pd

hts={}

for keyword in keywords:

    df2  = pd.read_csv('keywords/'+keyword+'.csv')
    
    hts[keyword] = list(df2['hashtag'].values[0:10])

    print hts[keyword]

['berniesanders', 'sanders', 'sanders2016', 'berniesanders2016', 'berniesandersforsc', 'berniesandersforpresident2016', 'sandersonhardball', 'janesanders', 'sanderstrumpdebatenow', 'berniesandersforpresident']
['bencarson', 'carson', 'bencarson2016', 'carson2016', 'votecarson', 'bencarson4prez', 'carson4prez', 'carsonstrong', 'respectcarson', 'drbencarson']
['hillaryclinton', 'clinton', 'billclinton', 'clintons', 'hilaryclinton', 'clintonemails', 'clinton2016', 'clintonfoundation', 'hillaryclintonlies', 'clintoncash']
['trump', 'trump2016', 'nevertrump', 'trumptrain', 'alwaystrump', 'donaldtrump', 'votetrump', 'dumptrump', 'realdonaldtrump', 'votetrump2016']
['randpaul', 'randpaul2016', 'randpaul2020', 'voterandpaul', 'randpaul2024', 'senrandpaul', 'imissrandpaul', 'belikerandpaul', 'randpaul16', 'randpaulcorvette']
['rubio', 'marcorubio', 'rubio2016', 'neverrubio', 'microsoftrubiofraud', 'robotrubio', 'rubiorobots', 'norubio', 'littlerubio', 'dumprubio']
['jebbush', 'bush', 'georgewbush', 'nomorebushes', 'tedbushie', 'bushcrimefamily', 'neilbush', 'bushman', 'gwbush', 'georgebush']
['chrischristie', 'christie', 'freechrischristie', 'christie2016', 'christiebrinkley', 'christieface', 'freechristie', 'christieendorsement', 'agathachristie', 'govchristie']
['huckabee', 'mikehuckabee', 'huckabee2016', 'huckabeevp', 'huckabee4vp', 'votehuckabee', 'huckabeeforvp', 'sarahhuckabeesanders', 'mike_huckabee', 'caucusforhuckabee']
['carlyfiorina', 'fiorina', 'cruzfiorina2016', 'cruzfiorina', 'carly_fiorina', 'rubiofiorina', 'fiorina2016', 'carleyfiorina', 'fiorinasurge', 'byefiorina']
['cruzcrew', 'tedcruz', 'cruz', 'choosecruz', 'cruz2016', 'cruztovictory', 'tedcruz2016', 'nevercruz', 'caucusforcruz', 'cruzfraud']
['kasich', 'johnkasich', 'kasich4us', 'kasich2016', 'kasichcan', 'neverkasich', 'dropoutkasich', 'kasichsurge', 'nokasich', '2016_kasich']
['omally4vp', 'martinomally']

In [4]:
keywordstrings = {}

for key, value in keywords.iteritems():
    keywordstrings[key] = '|'.join(value)

keywordstrings

{'Bush': 'jebbush|jeb|#bush',
 'Carson': 'ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson',
 'Christie': 'chrischristie|chris christie|christie2016|#christie',
 'Clinton': 'hillary|clinton',
 'Cruz': 'cruz',
 'Fiorina': 'carly|carlley|fiorina',
 'Huckabee': 'huckabee',
 'Kasich': 'kasich',
 'Omally': 'omally',
 'Randpaul': 'rand paul|randpaul',
 'Rubio': 'marco|rubio',
 'Sanders': 'bern|sanders',
 'Trump': 'trump'}

In [38]:
prequery = """CREATE CONSTRAINT ON (candidate:Candidate_{0}) ASSERT candidate.name IS UNIQUE"""

In [5]:
# query="""MATCH (t:Tweet_{0})<-[:TAGS]-(h:Hashtag_{0}) \
# WHERE ((h.name in {1}) OR (t.text =~ \"(?ism).*({2}).*\")) \
# SET t.mentions_{3} = true \
# RETURN count(t)"""

query="""MATCH (t:Tweet_{0}) \
WHERE (t.text =~ \"(?ism).*({1}).*\") \
SET t.mentions_{2} = true \
RETURN count(t)"""

In [6]:
partitions = ['2015_10_11', '2015_10_12', '2015_10_13', '2015_10_14', '2015_10_15',\
              '2016_1_26', '2016_1_27', '2016_1_28', '2016_1_29', '2016_1_30', '2016_2_2','2016_2_3', \
              '2016_2_4', '2016_2_5', '2016_2_6', '2016_2_7', '2016_2_8', '2016_2_9', '2016_2_10',\
              '2016_2_11', '2016_2_12', '2016_2_13', '2016_2_14', '2016_2_15', \
              '2016_2_23', '2016_2_24', '2016_2_25', '2016_2_26','2016_2_27', '2016_3_1', '2016_3_2',\
             '2016_3_3', '2016_3_4', '2016_3_5', '2016_3_6', '2016_3_7', '2016_3_8', '2016_3_9',\
             '2016_3_10', '2016_3_11']

# partitions = ['2016_2_24', '2016_2_25', '2016_2_26', '2016_3_1', '2016_3_2',\
#              '2016_3_3', '2016_3_4', '2016_3_5', '2016_3_6', '2016_3_7', '2016_3_8', '2016_3_9',\
#              '2016_3_10', '2016_3_11']

In [7]:
from neo4j.v1 import GraphDatabase, basic_auth
import time


def runprequery(driver, prequery):
    result = None
    try:
        session = driver.session()
        result = session.run(prequery)
        session.close()
        print 'completed'
    except:
        session.close()
        print 'Could not run query'


#driver = GraphDatabase.driver("bolt://sauce5.sdsc.edu", auth=basic_auth("neo4j", "lajolla"))
print 'opening driver...'
#driver = GraphDatabase.driver("bolt://sauce5.sdsc.edu", auth=basic_auth("neo4j", "lajolla"))
driver = GraphDatabase.driver("bolt://127.0.0.1")
print 'after opening driver...'

for partition in partitions:
#for partition in ['2016_3_2']:

#     prequery_formatted = prequery.format(partition)
#     print prequery_formatted
    
    #success = runprequery(driver,prequery_formatted)
        
    for candidate, keywords in keywordstrings.iteritems():
        
        start = time.time()
        
        #hashtags = hts[candidate]
        
        query_formatted = query.format(partition,keywords,candidate)
        print query_formatted
        
        session = driver.session()
        result = session.run(query_formatted)

        for record in result:
            print partition, candidate, record[0]

        session.close()
        
        end = time.time()
        print end - start

opening driver...
after opening driver...
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2015_10_11 Huckabee 92
0.396808862686
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2015_10_11 Sanders 5756
0.418828964233
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2015_10_11 Clinton 10351
0.434485912323
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2015_10_11 Trump 17298
0.382841825485
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2015_10_11 Cruz 2014
0.261349916458
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2015_10_11 Randpaul 256
0.343826055527
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2015_10_11 Bush 1454
0.395103931427
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2015_10_11 Christie 51
0.456007957458
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2015_10_11 Carson 2293
0.918210983276
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2015_10_11 Fiorina 364
0.393846035004
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2015_10_11 Rubio 663
0.341733932495
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2015_10_11 Kasich 120
0.244942188263
MATCH (t:Tweet_2015_10_11) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2015_10_11 Omally 0
0.245297908783
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2015_10_12 Huckabee 1360
4.69420385361
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2015_10_12 Sanders 71951
4.86847090721
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2015_10_12 Clinton 130195
5.21891212463
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2015_10_12 Trump 168388
4.40072202682
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2015_10_12 Cruz 24478
3.32228398323
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2015_10_12 Randpaul 3522
4.20317697525
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2015_10_12 Bush 11157
4.90884304047
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2015_10_12 Christie 2328
5.84896087646
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2015_10_12 Carson 25957
12.2122240067
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2015_10_12 Fiorina 4511
5.16235303879
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2015_10_12 Rubio 10275
4.36406087875
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2015_10_12 Kasich 1815
3.16979694366
MATCH (t:Tweet_2015_10_12) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2015_10_12 Omally 1
3.09685707092
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2015_10_13 Huckabee 1356
4.86698102951
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2015_10_13 Sanders 137179
6.32783102989
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2015_10_13 Clinton 217330
7.12970614433
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2015_10_13 Trump 239396
6.01861810684
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2015_10_13 Cruz 28945
4.37049102783
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2015_10_13 Randpaul 5225
5.73569512367
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2015_10_13 Bush 50847
7.06340694427
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2015_10_13 Christie 2000
7.24312496185
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2015_10_13 Carson 23568
15.0723059177
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2015_10_13 Fiorina 8369
6.52376699448
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2015_10_13 Rubio 11602
5.69830012321
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2015_10_13 Kasich 1717
3.98824191093
MATCH (t:Tweet_2015_10_13) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2015_10_13 Omally 11
4.08720684052
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2015_10_14 Huckabee 43283
8.66939496994
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2015_10_14 Sanders 673949
18.0384709835
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2015_10_14 Clinton 663003
15.3859670162
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2015_10_14 Trump 250074
9.33557605743
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2015_10_14 Cruz 24243
7.2386059761
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2015_10_14 Randpaul 4454
9.60833477974
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2015_10_14 Bush 22959
11.1372959614
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2015_10_14 Christie 1234
13.0380699635
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2015_10_14 Carson 16824
25.9077618122
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2015_10_14 Fiorina 9102
11.138338089
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2015_10_14 Rubio 10796
9.53080415726
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2015_10_14 Kasich 6251
6.78060913086
MATCH (t:Tweet_2015_10_14) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2015_10_14 Omally 51
6.8173289299
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2015_10_15 Huckabee 3342
1.07355594635
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2015_10_15 Sanders 75959
1.80072402954
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2015_10_15 Clinton 71547
1.83805513382
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2015_10_15 Trump 48188
1.33128094673
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2015_10_15 Cruz 8453
1.02608394623
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2015_10_15 Randpaul 927
1.33660793304
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2015_10_15 Bush 5545
1.55992698669
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2015_10_15 Christie 196
1.76960706711
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2015_10_15 Carson 4510
3.60474085808
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2015_10_15 Fiorina 938
1.54925298691
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2015_10_15 Rubio 2066
1.36074590683
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2015_10_15 Kasich 271
0.984724998474
MATCH (t:Tweet_2015_10_15) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2015_10_15 Omally 4
0.979555845261
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2016_1_26 Huckabee 2446
6.26651191711
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2016_1_26 Sanders 397183
10.7631311417
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2016_1_26 Clinton 405142
11.192127943
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2016_1_26 Trump 492433
11.9350759983
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2016_1_26 Cruz 139731
6.86885786057
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2016_1_26 Randpaul 18860
8.06375002861
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2016_1_26 Bush 17232
9.08665513992
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2016_1_26 Christie 11419
10.7324171066
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2016_1_26 Carson 5116
20.9468390942
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2016_1_26 Fiorina 6381
9.13040685654
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2016_1_26 Rubio 26050
8.0953669548
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2016_1_26 Kasich 5747
5.68051505089
MATCH (t:Tweet_2016_1_26) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2016_1_26 Omally 34
5.6236000061
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2016_1_27 Huckabee 8199
7.69860482216
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2016_1_27 Sanders 287076
11.0683870316
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2016_1_27 Clinton 230620
10.7764520645
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2016_1_27 Trump 1009655
18.2916178703
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2016_1_27 Cruz 192967
8.14315295219
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2016_1_27 Randpaul 11385
9.06924009323
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2016_1_27 Bush 24957
10.3019080162
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2016_1_27 Christie 7502
11.910394907
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2016_1_27 Carson 9035
23.873281002
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2016_1_27 Fiorina 4903
10.3243708611
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2016_1_27 Rubio 28719
9.10036420822
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2016_1_27 Kasich 6358
6.48393201828
MATCH (t:Tweet_2016_1_27) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2016_1_27 Omally 5
6.50273394585
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2016_1_28 Huckabee 25797
7.10315513611
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2016_1_28 Sanders 278782
10.102478981
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2016_1_28 Clinton 231885
9.59712791443
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2016_1_28 Trump 811613
12.0009360313
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2016_1_28 Cruz 174775
8.62704110146
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2016_1_28 Randpaul 10868
7.76496911049
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2016_1_28 Bush 24944
8.89610505104
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2016_1_28 Christie 3658
10.4503440857
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2016_1_28 Carson 7329
20.441767931
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2016_1_28 Fiorina 8339
9.06522512436
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2016_1_28 Rubio 40885
7.96664595604
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2016_1_28 Kasich 3659
5.46731805801
MATCH (t:Tweet_2016_1_28) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2016_1_28 Omally 2
5.52662801743
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2016_1_29 Huckabee 24943
10.5272359848
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2016_1_29 Sanders 248365
10.7159609795
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2016_1_29 Clinton 327094
11.3268840313
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(trump).*") SET t.mentions_Trump = true RETURN count(t)
2016_1_29 Trump 803571
12.5237619877
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(cruz).*") SET t.mentions_Cruz = true RETURN count(t)
2016_1_29 Cruz 236380
8.80850887299
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(rand paul|randpaul).*") SET t.mentions_Randpaul = true RETURN count(t)
2016_1_29 Randpaul 37981
9.52617287636
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(jebbush|jeb|#bush).*") SET t.mentions_Bush = true RETURN count(t)
2016_1_29 Bush 66831
10.8783051968
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(chrischristie|chris christie|christie2016|#christie).*") SET t.mentions_Christie = true RETURN count(t)
2016_1_29 Christie 20347
12.2617180347
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(ben carson|bencarson|bencarson|#carson|bencarson2016|carson2016|votecarson|bencarson4prez|carson4prez|carsonstrong|respectcarson|drbencarson).*") SET t.mentions_Carson = true RETURN count(t)
2016_1_29 Carson 29441
24.5486438274
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(carly|carlley|fiorina).*") SET t.mentions_Fiorina = true RETURN count(t)
2016_1_29 Fiorina 25493
10.9374909401
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(marco|rubio).*") SET t.mentions_Rubio = true RETURN count(t)
2016_1_29 Rubio 100244
9.97466993332
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(kasich).*") SET t.mentions_Kasich = true RETURN count(t)
2016_1_29 Kasich 13317
6.75957083702
MATCH (t:Tweet_2016_1_29) WHERE (t.text =~ "(?ism).*(omally).*") SET t.mentions_Omally = true RETURN count(t)
2016_1_29 Omally 9
6.68900084496
MATCH (t:Tweet_2016_1_30) WHERE (t.text =~ "(?ism).*(huckabee).*") SET t.mentions_Huckabee = true RETURN count(t)
2016_1_30 Huckabee 5717
5.20573997498
MATCH (t:Tweet_2016_1_30) WHERE (t.text =~ "(?ism).*(bern|sanders).*") SET t.mentions_Sanders = true RETURN count(t)
2016_1_30 Sanders 278480
8.50324201584
MATCH (t:Tweet_2016_1_30) WHERE (t.text =~ "(?ism).*(hillary|clinton).*") SET t.mentions_Clinton = true RETURN count(t)
2016_1_30 Clinton 369732
9.33593702316